/**
 * Builds the icon layer from the Heroicons package (MIT, © Tailwind Labs).
 *
 *   node packages/ui/scripts/build-icons.mjs
 *
 * Outputs (packages/ui/dist/icons/):
 *   sprite.svg      — one <symbol> per icon+variant. Reference EXTERNALLY so the browser
 *                     caches it once: <use href="/icons/sprite.svg#hi-bell-outline">.
 *                     (~620 KB for 1,296 symbols; inlining it on every page would be wrong.)
 *   {variant}/*.svg — one file per icon for <img>, CSS mask, or copy-paste
 *   manifest.json   — names, variants, grids; the MCP and the gallery read this
 *   icons.ts        — typed name union for the React <Icon>
 *
 * Icons are never edited by hand and never drawn ad hoc in templates: the guard in
 * scripts/check-templates.mjs rejects inline <svg><path> outside the icon component.
 * Colour comes from currentColor; weight from --icon-stroke-* (see FLAVOR.md), so an
 * icon beside 600-weight text renders 2px and beside 400-weight text 1.5px.
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { join, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, '..', '..', 'node_modules', 'heroicons');
const OUT = join(ROOT, 'dist', 'icons');
mkdirSync(OUT, { recursive: true });

const VARIANTS = [
  { key: 'outline', dir: '24/outline', grid: 24 },
  { key: 'solid',   dir: '24/solid',   grid: 24 },
  { key: 'mini',    dir: '20/solid',   grid: 20 },   // solid at 20 — dense UI
  { key: 'micro',   dir: '16/solid',   grid: 16 },   // solid at 16 — inline with text
];
const inner = (svg) => svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim();

const names = new Set();
const symbols = [];
for (const v of VARIANTS) {
  for (const f of readdirSync(join(SRC, v.dir)).filter((x) => x.endsWith('.svg'))) {
    const name = basename(f, '.svg'); names.add(name);
    const body = inner(readFileSync(join(SRC, v.dir, f), 'utf8'));
    // Outline keeps its stroke; solid variants are fills. Both inherit colour from
    // currentColor because the source files already use it — we only wrap in <symbol>.
    symbols.push(`<symbol id="hi-${name}-${v.key}" viewBox="0 0 ${v.grid} ${v.grid}"${v.key === 'outline' ? ' fill="none" stroke="currentColor"' : ' fill="currentColor"'}>${body}</symbol>`);
  }
}
// Also individual files, for <img src>, CSS mask-image, and agents that want one glyph.
for (const v of VARIANTS) {
  mkdirSync(join(OUT, v.key), { recursive: true });
  for (const f of readdirSync(join(SRC, v.dir)).filter((x) => x.endsWith('.svg'))) writeFileSync(join(OUT, v.key, f), readFileSync(join(SRC, v.dir, f)));
}
const sprite = `<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">\n<!-- Heroicons v2 (MIT) — generated by packages/ui/scripts/build-icons.mjs; do not edit -->\n${symbols.join('\n')}\n</svg>\n`;
writeFileSync(join(OUT, 'sprite.svg'), sprite);

const sorted = [...names].sort();
writeFileSync(join(OUT, 'manifest.json'), JSON.stringify({
  source: 'heroicons@2.2.0', license: 'MIT', count: sorted.length,
  variants: VARIANTS.map((v) => ({ key: v.key, grid: v.grid, use: v.key === 'outline' ? 'default state' : v.key === 'solid' ? 'active/selected state at 24' : v.key === 'mini' ? 'dense UI at 20' : 'inline with text at 16' })),
  names: sorted,
  contract: 'Outline is the default; solid marks the active/selected state. One SVG per icon, states via CSS colour — never separate assets per state. Direction-bearing glyphs (arrows, chevrons) get data-directional and mirror under dir=rtl.',
}, null, 2));
writeFileSync(join(OUT, 'icons.ts'), `// generated by packages/ui/scripts/build-icons.mjs — do not edit\nexport type IconName =\n  | ${sorted.map((n) => `'${n}'`).join('\n  | ')};\nexport type IconVariant = 'outline' | 'solid' | 'mini' | 'micro';\nexport const ICON_NAMES: readonly IconName[] = ${JSON.stringify(sorted)} as const;\n`);
console.log(`icons: ${sorted.length} names × ${VARIANTS.length} variants → sprite ${(sprite.length / 1024).toFixed(0)} KB`);
