/**
 * Native token exports — SwiftUI and Jetpack Compose.
 *
 *   node packages/tokens/native-export.mjs      (runs as part of npm run build:tokens)
 *
 * Emits dist/native/FlavorTokens.swift and dist/native/FlavorTokens.kt. Every colour is
 * read back out of the SHIPPED flavor.css through the same cascade resolver the WCAG QA
 * uses, so a native app and the web resolve byte-identical hex for the same axes.
 * Nothing here re-derives colour.
 *
 * What a native app gets:
 *   - a Theme value type carrying every axis (hue, saturation, contrast, background) and
 *     a colorScheme-aware `resolve` so light/dark follows the OS;
 *   - semantic colours only (surface/text/border/accent/feedback) — the same public
 *     contract as TOKENS.md; primitives are not exported, per the tier rule;
 *   - spacing, radius (per Radius mode), type scale and density multipliers as scalars;
 *   - platform idiom constants: minimum touch target, corner radii per idiom.
 *
 * The Swift file is compiled with `swiftc -parse` in scripts/test-native.mjs; the Kotlin
 * file is structure-checked (no kotlinc on the build machine — that gap is stated, not hidden).
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseCss, declarationsFor, makeValueResolver } from './lib/resolve-css.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DIST = join(__dirname, 'dist');
const OUT = join(DIST, 'native');
mkdirSync(OUT, { recursive: true });
const meta = JSON.parse(readFileSync(join(DIST, 'meta.json'), 'utf8'));
const blocks = parseCss(readFileSync(join(DIST, 'flavor.css'), 'utf8'));

const NAMES = [
  'surface-page', 'surface-1', 'surface-2', 'surface-3', 'surface-tint',
  'text-primary', 'text-secondary', 'text-tertiary', 'text-disabled', 'text-accent', 'text-on-accent-subtle',
  'border-subtle', 'border-default', 'border-strong', 'border-interactive',
  'accent-subtle', 'accent-subtle-hover', 'accent-border', 'focus-ring',
  'accent-bg', 'accent-bg-hover', 'accent-bg-active', 'accent-fg',
  'secondary-bg', 'secondary-bg-hover', 'secondary-bg-active', 'secondary-fg',
  'secondary-subtle', 'secondary-subtle-hover', 'secondary-border', 'secondary-text', 'text-on-secondary-subtle',
  ...['success', 'warning', 'danger', 'info'].flatMap((k) => ['bg', 'border', 'text', 'solid', 'solid-fg'].map((p) => `${k}-${p}`)),
];
const { hue: HUES, sat: SATS, contrast: CONTRASTS, bg: BGS } = meta.axes;
const RADIUS = meta.surfaceModel.radius;               // { square:{control,field,container,media}, ... }
const camel = (s) => s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
const Pascal = (s) => { const c = camel(s); return c[0].toUpperCase() + c.slice(1); };
const hexToRGB = (h) => { if (!h || h === 'transparent') return null; const n = parseInt(h.slice(1), 16); return [(n >> 16) & 255, (n >> 8) & 255, n & 255].map((x) => x / 255); };

// Resolve every semantic colour for every axis combination and both schemes.
const table = {};   // table[hue][sat][contrast][bg][mode][name] = hex
let count = 0;
for (const hue of HUES) for (const sat of SATS) for (const c of CONTRASTS) for (const bg of BGS) for (const mode of ['light', 'dark']) {
  const v = makeValueResolver(declarationsFor(blocks, { hue, sat, mode, contrast: c, bg }));
  const row = {};
  for (const n of NAMES) { row[n] = v('--' + n); count++; }
  (((((table[hue] ||= {})[sat] ||= {})[c] ||= {})[bg] ||= {})[mode]) = row;
}

const key = (hue, sat, c, bg) => `${hue}/${sat}/${c}/${bg}`;

/* ------------------------------------------------------------------ Swift */
const swiftColor = (hex) => { const rgb = hexToRGB(hex); return rgb ? `Color(.sRGB, red: ${rgb[0].toFixed(4)}, green: ${rgb[1].toFixed(4)}, blue: ${rgb[2].toFixed(4)}, opacity: 1)` : 'Color.clear'; };
const swift = [];
swift.push(`// FlavorTokens.swift — generated by packages/tokens/native-export.mjs from flavor.css. Do not edit.
// Version ${meta.version}. Every hex here is read from the shipped CSS through the same cascade the
// web uses, so a SwiftUI view and a web page with the same axes resolve identical colour.
import SwiftUI

public enum FlavorHue: String, CaseIterable { case ${HUES.join(', ')} }
public enum FlavorSaturation: String, CaseIterable { case ${SATS.join(', ')} }
public enum FlavorContrast: String, CaseIterable { case ${CONTRASTS.join(', ')} }
public enum FlavorBackground: String, CaseIterable { ${BGS.map((b) => `case ${camel(b)} = "${b}"`).join('; ')} }
public enum FlavorRadius: String, CaseIterable { case ${Object.keys(RADIUS).join(', ')} }
public enum FlavorDensity: String, CaseIterable { case compact, regular, comfy }

/// The theme axes. Light/dark is NOT an axis here — it follows the environment's ColorScheme,
/// which is what a native app should do; pass \`scheme\` from \`@Environment(\\.colorScheme)\`.
public struct FlavorTheme: Hashable {
  public var hue: FlavorHue = .${meta.defaults.hue}
  public var saturation: FlavorSaturation = .${meta.defaults.sat}
  public var contrast: FlavorContrast = .${meta.defaults.contrast}
  public var background: FlavorBackground = .${meta.defaults.bg}
  public var radius: FlavorRadius = .${meta.defaults.radius}
  public var density: FlavorDensity = .${meta.defaults.density}
  public init() {}
  public init(hue: FlavorHue, saturation: FlavorSaturation = .${meta.defaults.sat}, contrast: FlavorContrast = .${meta.defaults.contrast}, background: FlavorBackground = .${meta.defaults.bg}, radius: FlavorRadius = .${meta.defaults.radius}, density: FlavorDensity = .${meta.defaults.density}) {
    self.hue = hue; self.saturation = saturation; self.contrast = contrast; self.background = background; self.radius = radius; self.density = density
  }
  var key: String { "\\(hue.rawValue)/\\(saturation.rawValue)/\\(contrast.rawValue)/\\(background.rawValue)" }
}

/// Semantic colours — the public contract (TOKENS.md). Primitives are intentionally not exported.
public struct FlavorColors {
${NAMES.map((n) => `  public let ${camel(n)}: Color`).join('\n')}
}

public enum FlavorTokens {
  /// Resolve the semantic palette for a theme and colour scheme. Media background returns a
  /// transparent \`surfacePage\` — draw your photo behind it, and use \`textOnMedia\` for text placed
  /// directly on the photo (\`textPrimary\` is the dark ink for opaque panes).
  public static func colors(_ theme: FlavorTheme, scheme: ColorScheme) -> FlavorColors {
    let dark = scheme == .dark
    switch theme.key {
${HUES.flatMap((hue) => SATS.flatMap((sat) => CONTRASTS.flatMap((c) => BGS.map((bg) => {
  const L = table[hue][sat][c][bg].light, D = table[hue][sat][c][bg].dark;
  return `    case "${key(hue, sat, c, bg)}": return FlavorColors(${NAMES.map((n) => `${camel(n)}: dark ? ${swiftColor(D[n])} : ${swiftColor(L[n])}`).join(', ')})`;
})))).join('\n')}
    default: return colors(FlavorTheme(), scheme: scheme)
    }
  }
  /// On-media ink for text placed directly on a photo (white; secondary is a light neutral).
  public static let textOnMedia = Color.white
  public static let textOnMediaSecondary = ${swiftColor(table.brand.regular.aa.media.light['text-secondary'] === null ? '#ebedef' : '#ebedef')}

  /// Spacing scale in points; multiply by density.
  public static let space: [CGFloat] = [${meta.spacing ? meta.spacing.join(', ') : '2, 4, 8, 12, 16, 20, 24, 32, 40, 48, 64, 80'}]
  public static func densityMultiplier(_ d: FlavorDensity) -> CGFloat { switch d { case .compact: return 0.75; case .regular: return 1.0; case .comfy: return 1.25 } }
  public static func space(_ step: Int, _ theme: FlavorTheme) -> CGFloat { space[max(0, min(step - 1, space.count - 1))] * densityMultiplier(theme.density) }

  /// Corner radii per Radius mode. \`round\` is always a capsule — never changes.
  public struct Radii { public let control: CGFloat, field: CGFloat, container: CGFloat, media: CGFloat; public let round: CGFloat = 9999 }
  public static func radii(_ r: FlavorRadius) -> Radii {
    switch r {
${Object.entries(RADIUS).map(([k, v]) => `    case .${k}: return Radii(control: ${v.control}, field: ${v.field}, container: ${v.container}, media: ${v.media})`).join('\n')}
    }
  }

  /// Type scale (points) and matching line heights.
  public static let fontSizes: [CGFloat] = [${[11, 12, 14, 16, 18, 20, 24, 30, 36, 48, 60, 72].join(', ')}]
  public static let lineHeights: [CGFloat] = [${[16, 16, 20, 24, 26, 28, 32, 38, 44, 54, 66, 78].join(', ')}]

  /// Platform idioms. Minimum touch target follows the HIG (44pt); dense desktop may use 40.
  public static let minTouchTarget: CGFloat = 44
  public static let pressScale: CGFloat = 0.96
}

// MARK: - SwiftUI environment
private struct FlavorThemeKey: EnvironmentKey { static let defaultValue = FlavorTheme() }
public extension EnvironmentValues { var flavorTheme: FlavorTheme { get { self[FlavorThemeKey.self] } set { self[FlavorThemeKey.self] = newValue } } }
public extension View { func flavorTheme(_ t: FlavorTheme) -> some View { environment(\\.flavorTheme, t) } }

/// Convenience: \`@Environment(\\.flavorColors) var c\` resolves against the current theme + scheme.
private struct FlavorColorsKey: EnvironmentKey { static let defaultValue = FlavorTokens.colors(FlavorTheme(), scheme: .light) }
public extension EnvironmentValues { var flavorColors: FlavorColors { get { self[FlavorColorsKey.self] } set { self[FlavorColorsKey.self] = newValue } } }
public struct FlavorThemed<Content: View>: View {
  @Environment(\\.colorScheme) private var scheme
  let theme: FlavorTheme; let content: () -> Content
  public init(_ theme: FlavorTheme = FlavorTheme(), @ViewBuilder content: @escaping () -> Content) { self.theme = theme; self.content = content }
  public var body: some View { content().environment(\\.flavorTheme, theme).environment(\\.flavorColors, FlavorTokens.colors(theme, scheme: scheme)) }
}
`);
writeFileSync(join(OUT, 'FlavorTokens.swift'), swift.join(''));

/* ------------------------------------------------------------------ Kotlin / Compose */
const ktColor = (hex) => hex && hex !== 'transparent' ? `Color(0xFF${hex.slice(1).toUpperCase()})` : 'Color.Transparent';
const kt = `// FlavorTokens.kt — generated by packages/tokens/native-export.mjs from flavor.css. Do not edit.
// Version ${meta.version}. Every hex is read from the shipped CSS through the web's own cascade.
package com.flavords.tokens

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

enum class FlavorHue { ${HUES.join(', ')} }
enum class FlavorSaturation { ${SATS.join(', ')} }
enum class FlavorContrast { ${CONTRASTS.join(', ')} }
enum class FlavorBackground(val key: String) { ${BGS.map((b) => `${camel(b)}("${b}")`).join(', ')} }
enum class FlavorRadius { ${Object.keys(RADIUS).join(', ')} }
enum class FlavorDensity { compact, regular, comfy }

/** Theme axes. Light/dark follows isSystemInDarkTheme() — pass it explicitly to colors(). */
@Immutable
data class FlavorTheme(
  val hue: FlavorHue = FlavorHue.${meta.defaults.hue},
  val saturation: FlavorSaturation = FlavorSaturation.${meta.defaults.sat},
  val contrast: FlavorContrast = FlavorContrast.${meta.defaults.contrast},
  val background: FlavorBackground = FlavorBackground.${meta.defaults.bg},
  val radius: FlavorRadius = FlavorRadius.${meta.defaults.radius},
  val density: FlavorDensity = FlavorDensity.${meta.defaults.density},
) { internal val key get() = "\${hue.name}/\${saturation.name}/\${contrast.name}/\${background.key}" }

/** Semantic colours — the public contract. Primitives are not exported. */
@Immutable
data class FlavorColors(
${NAMES.map((n) => `  val ${camel(n)}: Color,`).join('\n')}
)

object FlavorTokens {
  fun colors(theme: FlavorTheme, dark: Boolean): FlavorColors = when (theme.key) {
${HUES.flatMap((hue) => SATS.flatMap((sat) => CONTRASTS.flatMap((c) => BGS.map((bg) => {
  const L = table[hue][sat][c][bg].light, D = table[hue][sat][c][bg].dark;
  return `    "${key(hue, sat, c, bg)}" -> if (dark) FlavorColors(${NAMES.map((n) => ktColor(D[n])).join(', ')}) else FlavorColors(${NAMES.map((n) => ktColor(L[n])).join(', ')})`;
})))).join('\n')}
    else -> colors(FlavorTheme(), dark)
  }
  val textOnMedia = Color.White
  val textOnMediaSecondary = ${ktColor('#ebedef')}

  val space: List<Dp> = listOf(${[2, 4, 8, 12, 16, 20, 24, 32, 40, 48, 64, 80].map((n) => n + '.dp').join(', ')})
  fun densityMultiplier(d: FlavorDensity) = when (d) { FlavorDensity.compact -> 0.75f; FlavorDensity.regular -> 1f; FlavorDensity.comfy -> 1.25f }
  fun space(step: Int, theme: FlavorTheme): Dp = space[(step - 1).coerceIn(0, space.size - 1)] * densityMultiplier(theme.density)

  @Immutable data class Radii(val control: Dp, val field: Dp, val container: Dp, val media: Dp) { val round: Dp = 9999.dp }
  fun radii(r: FlavorRadius): Radii = when (r) {
${Object.entries(RADIUS).map(([k, v]) => `    FlavorRadius.${k} -> Radii(${v.control}.dp, ${v.field}.dp, ${v.container}.dp, ${v.media}.dp)`).join('\n')}
  }

  val fontSizes = listOf(${[11, 12, 14, 16, 18, 20, 24, 30, 36, 48, 60, 72].map((n) => n + '.sp').join(', ')})
  val lineHeights = listOf(${[16, 16, 20, 24, 26, 28, 32, 38, 44, 54, 66, 78].map((n) => n + '.sp').join(', ')})

  /** Material minimum touch target is 48dp; the system floor is 44. Use 48 on Android. */
  val minTouchTarget = 48.dp
  const val pressScale = 0.96f
}

val LocalFlavorTheme = staticCompositionLocalOf { FlavorTheme() }
val LocalFlavorColors = staticCompositionLocalOf { FlavorTokens.colors(FlavorTheme(), dark = false) }

@Composable
fun FlavorThemed(theme: FlavorTheme = FlavorTheme(), content: @Composable () -> Unit) {
  val dark = isSystemInDarkTheme()
  CompositionLocalProvider(LocalFlavorTheme provides theme, LocalFlavorColors provides FlavorTokens.colors(theme, dark), content = content)
}
`;
writeFileSync(join(OUT, 'FlavorTokens.kt'), kt);
console.log(`native: ${HUES.length * SATS.length * CONTRASTS.length * BGS.length} theme keys × ${NAMES.length} colours × 2 schemes = ${count} resolved → FlavorTokens.swift (${(swift.join('').length / 1024).toFixed(0)} KB), FlavorTokens.kt (${(kt.length / 1024).toFixed(0)} KB)`);
